### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by 8la** [schachr/grafana-dashboards#1]
Hi, 

Im trying the dashboard and the cpu load shows on an acumulative way.. think it needs to be derived or some sort of scale.... i dont know what is netdata pushing to grapithe but the are not the values represented on netdata graphs.

![imagen](https://user-images.githubusercontent.com/315194/37596204-556fed4c-2b73-11e8-9c47-1967a06a4649.png)

**Comment by schachr** [comment]
Hello!

Sorry for my late answer!
I've tested it with VMs (Virtualbox) and a physical device but can not reproduce it.


Can you please provide some information to me:
- Have you aligned the update interval of netdata with graphite's storage schema?
- Are all other graphs working as expected?
- Provide details about your monitored device
- Remove value (100) of Y-Max (to see if it is ever increasing)

Thank you for your help to make it more reliable!

**Comment by 8la** [comment]
Hi!
### Update interval vs storage-schema
On `/etc/netdata/netdata.conf`: 
```
[backend]
        enabled = yes
        data source = as collected
        type = graphite
        destination = tcp:127.0.0.1:2003
        prefix = netdata
        hostname = 8la_es
        update every = 60
        buffer on failures = 10
        timeout ms = 20000
```
On `/opt/graphite/conf/storage-schema.conf`:
```
[default]
PATTERN = .*
RETENTIONS = 60s:1d,5m:365d
 ```

### Other graphs
The graphs doesn't work as expected. There seems to be some missconfiguration with the unit or the values coming from netdata. May be the dashboard does not work with `data source = as collected`and needs *average* or *sum* ?

There you have some examples: 

![imagen](https://user-images.githubusercontent.com/315194/38856473-7aa61c0a-421e-11e8-97d0-bc7dbe685934.png)

My /dev/vda is 29G and look at the disk graph: 
![imagen](https://user-images.githubusercontent.com/315194/38857627-a56f717c-4221-11e8-811b-86f46d246606.png)


![imagen](https://user-images.githubusercontent.com/315194/38856523-9b14ce14-421e-11e8-95e1-b78d462eaba7.png)

### Monitored device
Digital Ocean Droplet 


### Removing de 100 limit on Y: 
![imagen](https://user-images.githubusercontent.com/315194/38856429-5cf22f0a-421e-11e8-8641-597fd0f74b03.png)

Let me know if you need more info

**Comment by schachr** [comment]
I think you assumption is correct.
Please test
```
    data source = average
```
for the `[backend]` section on the netdata side.

Additionally I've set
```
    send names instead of ids = yes
```
although I do not know what the default for this setting is as it is not explained in the documentation ( [link](https://github.com/firehol/netdata/wiki/netdata-backends) )

So for reference here is my block:
```
[backend]
    enabled = yes
    type = graphite
    data source = average
    destination = 10.47.5.221
    prefix = netdata
    update every = 10
    buffer on failures = 100
    timeout ms = 20000
    send names instead of ids = yes
    send charts matching = *
```


Looking forward for your results.

**Comment by 8la** [comment]
Changing to average the **data source** param on **[backend]** did the trick! 

The only thing is that if i have peak values on that 60s interval... average will cut those values... but at least i have readable data now!

![imagen](https://user-images.githubusercontent.com/315194/38866775-e656d898-4239-11e8-91af-8c33a64445fa.png)

Thanks a lot!
